//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string product_name { get; set; }
        public string image_url { get; set; }
        public string brand { get; set; }
        public int category { get; set; }
        public int sub_category { get; set; }
        public string weight { get; set; }
        public decimal cost_price { get; set; }
        public decimal sell_price { get; set; }
        public bool status { get; set; }
        public Nullable<int> Stock { get; set; }
    }
}
