//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class selling_history
    {
        public int id { get; set; }
        public Nullable<int> dealer_id { get; set; }
        public int product_id { get; set; }
        public int quantity { get; set; }
        public decimal credit { get; set; }
        public decimal debit { get; set; }
        public int transaction_type { get; set; }
        public string customer_info { get; set; }
        public string payment_type { get; set; }
        public System.DateTime payment_date { get; set; }
        public string customer_name { get; set; }
        public string remarks { get; set; }
    
        public virtual dealer dealer { get; set; }
    }
}
